name: Docker v2

on:
  push:

jobs:
  base:
    runs-on: self-hosted
    strategy:
      matrix:
        target:
          - builder
          - node_prod_base
          - go_prod_base
    steps:
      - uses: TooMuch4U/actions-clean@v2.1
      - uses: actions/checkout@v3

      - run: |
          docker build -f ./base.Dockerfile \
          -t twir-base:${{ matrix.target }} \
          --target ${{ matrix.target }} \
          --cache-from type=gha,scope=twir-base:${{ matrix.target }} \
          --cache-to type=gha,mode=max,scope=twir-base:${{ matrix.target }} \
          .

  backend:
    runs-on: self-hosted
    needs:
      - base
    strategy:
      matrix:
        target:
          - api
          - bots
          - discord
          - emotes-cacher
          - eval
          - events
          - eventsub
          - integrations
          - language-detector
          - parser
          - scheduler
          - timers
          - tokens
          - websockets
          - ytsr
    steps:
      - uses: TooMuch4U/actions-clean@v2.1
      - uses: actions/checkout@v3
      - run: |
          docker build -f ./apps/${{ matrix.target }}/Dockerfile \
          -t ${{ secrets.DOCKER_REGISTRY }}/twir/${{ matrix.target }}:latest \
          .

  frontend:
    runs-on: self-hosted
    needs:
      - base
    strategy:
      matrix:
        target:
          - dashboard
          - landing
          - overlays
          - public-page
    steps:
      - uses: TooMuch4U/actions-clean@v2.1
      - uses: actions/checkout@v3
      - run: |
          docker build -f ./frontend/${{ matrix.target }}/Dockerfile \
          -t ${{ secrets.DOCKER_REGISTRY }}/twir/${{ matrix.target }}:latest \
          .

  migrations:
    runs-on: self-hosted
    needs:
      - base
    steps:
      - uses: TooMuch4U/actions-clean@v2.1
      - uses: actions/checkout@v3
      - run: |
          docker build -f ./migrations/Dockerfile \
          -t twir:migrations:latest \
          --cache-from type=gha,scope=twir-migrations \
          --cache-to type=gha,mode=max,scope=twir-migrations \
          .

  postgres-backup:
    runs-on: self-hosted
    steps:
      - uses: TooMuch4U/actions-clean@v2.1
      - uses: actions/checkout@v3
      - run: |
          docker build -f ./tools/pg-backup/Dockerfile \
          -t ${{ secrets.DOCKER_REGISTRY }}/twir/postgres-backup:latest \
          --cache-from type=gha,scope=twir-postgres-backup \
          --cache-to type=gha,mode=max,scope=twir-postgres-backup \
          .
